# About Me  

My name is **Federico Barusolo**, and I’m a **Computer Engineer** with a Master of Science (MoS) path specializing in **Artificial Intelligence, Data Science, Machine Learning**.  

I studied at **Politecnico di Milano** (2013-2018), worked in consultancy (2018-2021) and startup (2021 to date).

In [1]:
# Env requirements
!pip install numpy
!pip install pandas
!pip install scikit-learn
!pip install nltk
!pip install transformers
!pip install bertviz
#!conda install pytorch torchvision -c pytorch

Requirement already satisfied: numpy in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (2.2.4)
Requirement already satisfied: pandas in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from pandas) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: scikit-learn in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from scikit-learn) (2.2.4)
Requirement already satisfied: scipy>=1.6.0 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: nltk in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (3.9.1)
Requirement already satisfied: click in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from nltk) (4.67.1)
Requirement already satisfied: transformers in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (4.50.2)
Requirement already satisfied: filelock in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from transformers) (0.29.3)
Requirement already satisfied: numpy>=1.17 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from transformers) (2.2.4)
Requirement already satisfied: packaging>=20.0 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from requests->transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from requests->transformers) (2025.1.31)
Requirement already satisfied: bertviz in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (1.4.0)
Requirement already satisfied: transformers>=2.0 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from bertviz) (4.50.2)
Requirement already satisfied: torch>=1.0 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from bertviz) (2.6.0)
Requirement already satisfied: tqdm in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from bertviz) (4.67.1)
Requirement already satisfied: boto3 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from bertviz) (1.37.21)
Requirement already satisfied: requests in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from bertviz) (2.32.3)
Requirement already satisfied: regex in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from bertviz) (2024.11.6)
Requirement already satisfied: sentencepiece in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from bertviz) (0.2.0)
Requirement already satisfied: filelock in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from torch>=1.0->bertviz) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from torch>=1.0->bertviz) (4.12.2)
Requirement already satisfied: networkx in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from torch>=1.0->bertviz) (3.4.2)
Requirement already satisfied: jinja2 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from torch>=1.0->bertviz) (3.1.6)
Requirement already satisfied: fsspec in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from torch>=1.0->bertviz) (2025.3.0)
Requirement already satisfied: setuptools in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from torch>=1.0->bertviz) (75.8.0)
Requirement already satisfied: sympy==1.13.1 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from torch>=1.0->bertviz) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from sympy==1.13.1->torch>=1.0->bertviz) (1.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from transformers>=2.0->bertviz) (0.29.3)
Requirement already satisfied: numpy>=1.17 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from transformers>=2.0->bertviz) (2.2.4)
Requirement already satisfied: packaging>=20.0 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from transformers>=2.0->bertviz) (24.2)
Requirement already satisfied: pyyaml>=5.1 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from transformers>=2.0->bertviz) (6.0.2)
Requirement already satisfied: tokenizers<0.22,>=0.21 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from transformers>=2.0->bertviz) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from transformers>=2.0->bertviz) (0.5.3)
Requirement already satisfied: botocore<1.38.0,>=1.37.21 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from boto3->bertviz) (1.37.21)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from boto3->bertviz) (1.0.1)
Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from boto3->bertviz) (0.11.4)
Requirement already satisfied: charset-normalizer<4,>=2 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from requests->bertviz) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from requests->bertviz) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from requests->bertviz) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from requests->bertviz) (2025.1.31)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from botocore<1.38.0,>=1.37.21->boto3->bertviz) (2.9.0.post0)
Requirement already satisfied: MarkupSafe>=2.0 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from jinja2->torch>=1.0->bertviz) (3.0.2)
Requirement already satisfied: six>=1.5 in ./miniconda3/envs/bootcamp-env/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.38.0,>=1.37.21->boto3->bertviz) (1.16.0)

In [2]:
import re
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
import warnings as wn

wn.filterwarnings("ignore")

# Text Mining

# 📖 Introduction to Text Mining  

## What is Text Mining?  

**Text Mining** is a set of techniques and methodologies used to extract meaningful information from unstructured textual data. By leveraging **natural language processing (NLP), machine learning, and statistical analysis**, text mining enables the identification of patterns, relationships, and valuable insights within text data.  

## Applications  
Text mining is widely used across various fields, including:  
- **Automatic document classification** for organizing and managing large volumes of information
- **Information Retrieval** to find documents matching some specific queries  
- **Information extraction** to identify names, locations, events, and key concepts in text
- **Sentiment analysis** to understand opinions and trends in social media and reviews
- **Fraud detection and anomaly recognition** to uncover hidden patterns in financial or legal documents
- **Natural Language Understanding and Generation** (arguably the hottest trends right now)

Text mining plays a crucial role in transforming raw text into actionable knowledge, driving data-driven decision-making.

#### Structured Data v Unstructured Data

In [3]:
# Create a structured dataset (CSV format)
data = {
    "Name": ["Alice", "Bob", "Charlie", "Carol"],
    "Age": [25, 30, 35, 40],
    "Salary": [50000, 60000, 70000, 80000]
}

df = pd.DataFrame(data)

# Display the structured data
print("Structured Data (Tabular Format):")
display(df)

Structured Data (Tabular Format):

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
3    Carol   40   80000

In [4]:
# Compute the average Salary
average_salary = df["Salary"].mean()
print(f"\nAverage Salary: {average_salary}")

Average Salary: 65000.0

In [5]:
# Extract the age of Charlie
df_by_name = df.set_index("Name")
charlies_age = df_by_name.loc["Charlie"].Age

print(f"\nCharlie's age: {charlies_age}")

Charlie's age: 35

In [6]:
# Simple example of "unstructured" text
text_data = """
Alice is 25 years old and earns $50,000. Bob is 30 years old and earns $60,000.
Charlie is 35 years old and earns $70,000. Carol is 40 years old and earns $80,000.
"""

print(text_data)

Alice is 25 years old and earns $50,000. Bob is 30 years old and earns $60,000.
Charlie is 35 years old and earns $70,000. Carol is 40 years old and earns $80,000.

In [7]:
# Obtain the previous Name-Age-Salary table from the given text

# Regular expression to extract (Name, Age, Salary)
pattern = r"([A-Z][a-z]+) is (\d{1,3}) years old and earns \$(\d{1,10}(?:,\d{3})*)"

# Find all matches
matches = re.findall(pattern, text_data)

# Process extracted triples
triples = [(name, int(age), int(salary.replace(',', ''))) for name, age, salary in matches]

df = pd.DataFrame(triples, columns=["Name", "Age", "Salary"])
display(df)

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
3    Carol   40   80000

In [8]:
# Real-world unstructured text
text_data = """
Alice is 25 years old and earns $50,000. She has less experience than Bob, who's 30, 
and has a salary of $60000. Then Charlie (35) earns 70k dollars annually, and Carol, who's
forty years old, is the most senior and therefore earns $10,000 more than Charlie.
"""

print(text_data)

Alice is 25 years old and earns $50,000. She has less experience than Bob, who's 30,
and has a salary of $60000. Then Charlie (35) earns 70k dollars annually, and Carol, who's
forty years old, is the most senior and therefore earns $10,000 more than Charlie.

## Did You Know?  
Approximately **80% of the world's data is unstructured**! Unlike structured data, which is neatly organized in tables and databases, unstructured data lacks a predefined format, making it more complex to process and analyze.

## Examples of textual unstructured data:

1. **Documents** - PDFs, Word documents, notes, even phisical documents.
2. **Books** - Ebooks, book scans.
3. **Social Media Posts** – Posts, statuses, captions and comments.
4. **Web Pages & Articles** – Blogs, news articles, and online documentation.
5. **Chat Conversations** – WhatsApp, Telegram, Slack, SMS.
6. **Emails** – Text, attachments, and metadata in an unstructured format.
7. **Reviews** - Music, movies, books, restaurants, travel, shopping.

## Other examples
1. **Audio Recordings** – Podcasts, voice messages, and customer service call recordings.
2. **Video Recordings** - Youtube videos, movies, meetings.

## Document Representation

#### Bag-of-words (BoW)

Bag of Words (BoW) is a text representation model used in NLP. It represents a document as a set of words, ignoring grammar and word order. Each document is converted into a vector based on word frequency from a predefined vocabulary. While simple and effective for many tasks, BoW does not capture word meaning or context.

In [9]:
text_data = """
Bad is so bad, that we cannot but think good an accident; 
good is so good, that we feel certain that evil could be explained.
"""

print(text_data)

Bad is so bad, that we cannot but think good an accident;
good is so good, that we feel certain that evil could be explained.

In [10]:
# perform some basic cleaning
clean_text = text_data.replace("\n", "")
clean_text = clean_text.lower()
clean_text = re.sub(r"[^\w\s]", "", clean_text)

# create a vocabulary
vocabulary = set(clean_text.split(" "))
print(f"vocabulary: {vocabulary}")

vocabulary: {'evil', 'so', 'bad', 'think', 'we', 'feel', 'good', 'explained', 'but', 'be', 'accident', 'an', 'cannot', 'could', 'certain', 'is', 'that'}

In [11]:
# transform the text into a BoW
bow = []
for word in vocabulary:
    bow.append((word, len(re.findall(rf'\b{re.escape(word)}\b', clean_text))))

# sort by occurrences and then alphabetically
print(sorted(bow, key=lambda x: (-x[1], x[0])))

[('good', 3), ('that', 3), ('bad', 2), ('is', 2), ('so', 2), ('we', 2), ('accident', 1), ('an', 1), ('be', 1), ('but', 1), ('cannot', 1), ('certain', 1), ('could', 1), ('evil', 1), ('explained', 1), ('feel', 1), ('think', 1)]

In [12]:
# ... or just use the proper tools
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform([clean_text])

bow = list(zip(vectorizer.get_feature_names_out(), [int(x) for x in X.toarray()[0]]))
result = sorted(bow, key=lambda x: (-x[1], x[0]))
print(result)

[('good', 3), ('that', 3), ('bad', 2), ('is', 2), ('so', 2), ('we', 2), ('accident', 1), ('an', 1), ('be', 1), ('but', 1), ('cannot', 1), ('certain', 1), ('could', 1), ('evil', 1), ('explained', 1), ('feel', 1), ('think', 1)]

#### Term Frequency

In [13]:
# Compute the frequency of each term in text
document_len = len(clean_text.split(" "))

tf = [(couple[0], round(couple[1]/document_len, 2)) for couple in result]

print(tf)

[('good', 0.12), ('that', 0.12), ('bad', 0.08), ('is', 0.08), ('so', 0.08), ('we', 0.08), ('accident', 0.04), ('an', 0.04), ('be', 0.04), ('but', 0.04), ('cannot', 0.04), ('certain', 0.04), ('could', 0.04), ('evil', 0.04), ('explained', 0.04), ('feel', 0.04), ('think', 0.04)]

#### Term Frequency - Inverse Document Frequency

TF-IDF is a statistical measure used to evaluate how important a word is to a document in a collection (or corpus). It balances the frequency of a term within a document and its rarity across the entire corpus, helping to highlight significant terms.

TF-IDF = TF(t, d) * IDF(t) = TF(t, d) * log(N/DF(t))

where:
- TF(t, d): frequency of term t in document d
- IDF(t): inverse frequency of term t across all documents
- N: number of documents
- DF(t): number of documents containing term t
- the logarithm aims at dampening the effect of inverse document frequency

In [14]:
documents = [
"""
Recipe: Carbonara; Ingredients: pasta, guanciale, eggs, pecorino romano cheese, black pepper, salt.
""",

"""
The ingredients you need to use to make this recipe (Carbonara) are: pasta, eggs, roman pecorino, guanciale, salt and black pepper.
""",

"""
Recipe - the Carbonara: eggs, cream, guanciale, pasta, salt, pecorino cheese, black pepper.
""",

"""
For making carbonara you need these ingredients: egg, guanciale, pasta, salt, pecorino roman cheese and black pepper.
""",

"""
To make roman carbonara you need to use the eggs, guanciale, pecorino, pasta, salt and pepper.
"""]

for ix, doc in enumerate(documents):
    print(f"Document {ix + 1}: {doc}")

Document 1:
Recipe: Carbonara; Ingredients: pasta, guanciale, eggs, pecorino romano cheese, black pepper, salt.

Document 2:
The ingredients you need to use to make this recipe (Carbonara) are: pasta, eggs, roman pecorino, guanciale, salt and black pepper.

Document 3:
Recipe - the Carbonara: eggs, cream, guanciale, pasta, salt, pecorino cheese, black pepper.

Document 4:
For making carbonara you need these ingredients: egg, guanciale, pasta, salt, pecorino roman cheese and black pepper.

Document 5:
To make roman carbonara you need to use the eggs, guanciale, pecorino, pasta, salt and pepper.

In [15]:
# perform same cleaning as before
clean_documents = [re.sub(r"[^\w\s]", "", x.replace("\n", "").lower()) for x in documents]
print(clean_documents)

['recipe carbonara ingredients pasta guanciale eggs pecorino romano cheese black pepper salt', 'the ingredients you need to use to make this recipe carbonara are pasta eggs roman pecorino guanciale salt and black pepper', 'recipe  the carbonara eggs cream guanciale pasta salt pecorino cheese black pepper', 'for making carbonara you need these ingredients egg guanciale pasta salt pecorino roman cheese and black pepper', 'to make roman carbonara you need to use the eggs guanciale pecorino pasta salt and pepper']

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Create a TfidfVectorizer object
vectorizer = TfidfVectorizer()

# Fit and transform the documents
tfidf_matrix = vectorizer.fit_transform(clean_documents)

# Get the feature names (words)
feature_names = vectorizer.get_feature_names_out()

# Convert the result to a dense array (optional, but easier to read)
dense_matrix = tfidf_matrix.todense()

# Print the TF-IDF matrix with corresponding words
df = pd.DataFrame(dense_matrix, index=[f"doc{x+1}" for x in range(len(clean_documents))], columns=feature_names)

print("\nTF-IDF DataFrame:")
df.round(3)

TF-IDF DataFrame:

,and,are,black,carbonara,cheese,cream,egg,eggs,for,guanciale,ingredients,make,making,need,pasta,pecorino,pepper,recipe,roman,romano,salt,the,these,this,to,use,you
doc1,0.000,0.000,0.270,0.229,0.321,0.00,0.000,0.270,0.000,0.229,0.321,0.000,0.000,0.000,0.229,0.229,0.229,0.321,0.000,0.48,0.229,0.000,0.000,0.000,0.000,0.000,0.000
doc2,0.202,0.301,0.170,0.143,0.000,0.00,0.000,0.170,0.000,0.143,0.202,0.243,0.000,0.202,0.143,0.143,0.143,0.202,0.202,0.00,0.143,0.202,0.000,0.301,0.486,0.243,0.202
doc3,0.000,0.000,0.270,0.229,0.321,0.48,0.000,0.270,0.000,0.229,0.000,0.000,0.000,0.000,0.229,0.229,0.229,0.321,0.000,0.00,0.229,0.321,0.000,0.000,0.000,0.000,0.000
doc4,0.231,0.000,0.195,0.165,0.231,0.00,0.346,0.000,0.346,0.165,0.231,0.000,0.346,0.231,0.165,0.165,0.165,0.000,0.231,0.00,0.165,0.000,0.346,0.000,0.000,0.000,0.231
doc5,0.239,0.000,0.000,0.170,0.000,0.00,0.000,0.201,0.000,0.170,0.000,0.288,0.000,0.239,0.170,0.170,0.170,0.000,0.239,0.00,0.170,0.239,0.000,0.000,0.577,0.288,0.239

## Further pre-processing

### Stemming

Stemming is a text normalization technique in **Natural Language Processing (NLP)** that reduces words to their root or base form. It helps in **reducing inflected or derived words** to a common base, which improves text analysis tasks such as search and classification.

For example:
- **"running" → "run"**
- **"flies" → "fli"** (stemming may not always produce a valid word)
- **"better" → "better"** (stemming does not handle lemmatization)

One of the most commonly used stemming algorithms is **Porter’s Stemmer**, which applies a set of rules to remove common suffixes from words.

In [17]:
import nltk
from nltk.stem import PorterStemmer

# Download necessary NLTK data (if not already done)
nltk.download('punkt')

# Initialize the stemmer
stemmer = PorterStemmer()

# Example words for stemming
word = "cooking"

print(f"stemmed version of {word}: {stemmer.stem(word)}")

stemmed version of cooking: cook

[nltk_data] Downloading package punkt to /Users/federico/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [18]:
# use the Porter Stemmer to stem the documents in our collection
split_documents = [x.split(" ") for x in clean_documents]
stemmed_documents = [" ".join([stemmer.stem(word) for word in doc]) for doc in split_documents]

print(stemmed_documents)

['recip carbonara ingredi pasta guancial egg pecorino romano chees black pepper salt', 'the ingredi you need to use to make thi recip carbonara are pasta egg roman pecorino guancial salt and black pepper', 'recip  the carbonara egg cream guancial pasta salt pecorino chees black pepper', 'for make carbonara you need these ingredi egg guancial pasta salt pecorino roman chees and black pepper', 'to make roman carbonara you need to use the egg guancial pecorino pasta salt and pepper']

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Create a TfidfVectorizer object
vectorizer = TfidfVectorizer()

# Fit and transform the documents
tfidf_matrix = vectorizer.fit_transform(stemmed_documents)

# Get the feature names (words)
feature_names = vectorizer.get_feature_names_out()

# Convert the result to a dense array (optional, but easier to read)
dense_matrix = tfidf_matrix.todense()

# Print the TF-IDF matrix with corresponding words
df = pd.DataFrame(dense_matrix, index=[f"doc{x+1}" for x in range(len(stemmed_documents))], columns=feature_names)

print("\nTF-IDF DataFrame:")
df.round(3)

TF-IDF DataFrame:

,and,are,black,carbonara,chees,cream,egg,for,guancial,ingredi,make,need,pasta,pecorino,pepper,recip,roman,romano,salt,the,these,thi,to,use,you
doc1,0.000,0.000,0.273,0.231,0.325,0.000,0.231,0.000,0.231,0.325,0.000,0.000,0.231,0.231,0.231,0.325,0.000,0.485,0.231,0.000,0.000,0.000,0.000,0.000,0.000
doc2,0.204,0.305,0.172,0.145,0.000,0.000,0.145,0.000,0.145,0.204,0.204,0.204,0.145,0.145,0.145,0.204,0.204,0.000,0.145,0.204,0.000,0.305,0.492,0.246,0.204
doc3,0.000,0.000,0.273,0.231,0.325,0.485,0.231,0.000,0.231,0.000,0.000,0.000,0.231,0.231,0.231,0.325,0.000,0.000,0.231,0.325,0.000,0.000,0.000,0.000,0.000
doc4,0.252,0.000,0.212,0.180,0.252,0.000,0.180,0.377,0.180,0.252,0.252,0.252,0.180,0.180,0.180,0.000,0.252,0.000,0.180,0.000,0.377,0.000,0.000,0.000,0.252
doc5,0.244,0.000,0.000,0.174,0.000,0.000,0.174,0.000,0.174,0.000,0.244,0.244,0.174,0.174,0.174,0.000,0.244,0.000,0.174,0.244,0.000,0.000,0.588,0.294,0.244

## Stopword Removal

Stopwords are **common words** (e.g., *"the"*, *"is"*, *"and"*) that **do not carry significant meaning** and are often removed in text preprocessing for **Natural Language Processing (NLP)** tasks.

### Why Remove Stopwords?
- They appear frequently but contribute **little to meaning**.
- Removing them helps **reduce text size** and **improve model performance** in tasks like search, classification, and sentiment analysis.

### Example of Stopwords:
- **English:** *"the", "is", "in", "and", "a", "to", "of"*
- **Spanish:** *"el", "la", "y", "de", "en"*
- Different languages have different sets of stopwords.

In [20]:
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words("english"))

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/federico/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [21]:
# Import necessary libraries
import nltk
from nltk.tokenize import word_tokenize

# Function to remove stopwords
def remove_stopwords(doc):
    # Tokenize the document
    words = doc.split(" ")
    
    # Remove stopwords by filtering out the words that are in the stopword list
    filtered_words = [word for word in words if word not in stop_words and word.isalpha()]
    
    # Join the words back into a string
    return ' '.join(filtered_words)

# Apply stopword removal to each document
cleaned_documents = [remove_stopwords(doc) for doc in clean_documents]

In [22]:
# Stem documents
split_documents = [x.split(" ") for x in cleaned_documents]
stemmed_documents = [" ".join([stemmer.stem(word) for word in doc]) for doc in split_documents]

# Show the cleaned documents
for i, doc in enumerate(stemmed_documents):
    print(f"Document {i+1}: {doc}")

Document 1: recip carbonara ingredi pasta guancial egg pecorino romano chees black pepper salt
Document 2: ingredi need use make recip carbonara pasta egg roman pecorino guancial salt black pepper
Document 3: recip carbonara egg cream guancial pasta salt pecorino chees black pepper
Document 4: make carbonara need ingredi egg guancial pasta salt pecorino roman chees black pepper
Document 5: make roman carbonara need use egg guancial pecorino pasta salt pepper

In [23]:
# Create a TfidfVectorizer object
vectorizer = TfidfVectorizer()

# Fit and transform the documents
tfidf_matrix = vectorizer.fit_transform(stemmed_documents)

# Get the feature names (words)
feature_names = vectorizer.get_feature_names_out()

# Convert the result to a dense array (optional, but easier to read)
dense_matrix = tfidf_matrix.todense()

# Print the TF-IDF matrix with corresponding words
df = pd.DataFrame(dense_matrix, index=[f"doc{x+1}" for x in range(len(stemmed_documents))], columns=feature_names)

print("\nTF-IDF DataFrame:")
df.round(3)

TF-IDF DataFrame:

,black,carbonara,chees,cream,egg,guancial,ingredi,make,need,pasta,pecorino,pepper,recip,roman,romano,salt,use
doc1,0.273,0.231,0.325,0.000,0.231,0.231,0.325,0.000,0.000,0.231,0.231,0.231,0.325,0.000,0.485,0.231,0.000
doc2,0.257,0.217,0.000,0.000,0.217,0.217,0.306,0.306,0.306,0.217,0.217,0.217,0.306,0.306,0.000,0.217,0.368
doc3,0.289,0.244,0.343,0.513,0.244,0.244,0.000,0.000,0.000,0.244,0.244,0.244,0.343,0.000,0.000,0.244,0.000
doc4,0.277,0.234,0.329,0.000,0.234,0.234,0.329,0.329,0.329,0.234,0.234,0.234,0.000,0.329,0.000,0.234,0.000
doc5,0.000,0.252,0.000,0.000,0.252,0.252,0.000,0.354,0.354,0.252,0.252,0.252,0.000,0.354,0.000,0.252,0.426

#### Cosine Similarity

**Cosine Similarity** measures the similarity between two vectors (words or text documents) by calculating the cosine of the angle between their vector representations. It is commonly used in NLP for comparing document or word similarity.

The formula for cosine similarity is:

![Cosine Similarity Formula](https://media2.dev.to/dynamic/image/width=800%2Cheight=%2Cfit=scale-down%2Cgravity=auto%2Cformat=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fde1b2p11n8juy2cl6cy1.png)

#### Interpretation:
- **1**: Vectors are identical.
- **0**: Vectors are orthogonal (completely dissimilar).
- **-1**: Vectors are exactly opposite.


![Cosine Similarity Examples](https://storage.googleapis.com/lds-media/images/cosine-similarity-vectors.original.jpg)

In [24]:
from sklearn.metrics.pairwise import cosine_similarity

word1 = "carbonara"
word2 = "pasta"

word_index1 = vectorizer.vocabulary_.get(word1)
word_index2 = vectorizer.vocabulary_.get(word2)

if word_index1 is not None and word_index2 is not None:
    # Get the TF-IDF vector for the two words
    word_tfidf_vector1 = tfidf_matrix[:, word_index1].toarray().reshape(1, -1)  # Reshaping to make it a 2D array (1xN)
    word_tfidf_vector2 = tfidf_matrix[:, word_index2].toarray().reshape(1, -1)  # Reshaping to make it a 2D array (1xN)

    # Calculate cosine similarity
    cosine_sim_words = cosine_similarity(word_tfidf_vector1, word_tfidf_vector2)

    print(f"Cosine similarity between the word '{word1}' and the word '{word2}': {cosine_sim_words}'")
else:
    print(f"The words are not in the TF-IDF vocabulary.")

Cosine similarity between the word 'carbonara' and the word 'pasta': [[1.]]'

## Questions

1. what are the two most similar documents in the list? why do you think that is?
2. add a new document to the list such that:
    - the score of the stem 'egg' in the new document is higher than it is in all other documents;
    - cosine similarity between words 'carbonara' and 'pasta' drops below 1.

In [25]:
# The solution found by Erica was actually waaaaaay better than this ;) 

doc_matrix = pd.DataFrame(index=[f"doc{x+1}" for x in range(len(stemmed_documents))], columns=[f"doc{x+1}" for x in range(len(stemmed_documents))])

for id1, doc1 in enumerate([f"doc{x+1}" for x in range(len(stemmed_documents))]):
    for id2, doc2 in enumerate([f"doc{x+1}" for x in range(len(stemmed_documents))]):
        if doc1 != doc2:
            doc_tfidf_vector1 = tfidf_matrix[id1,:].toarray().reshape(1, -1)  # Reshaping to make it a 2D array (1xN)
            doc_tfidf_vector2 = tfidf_matrix[id2,:].toarray().reshape(1, -1)
            
            doc_matrix.loc[doc1, doc2] = cosine_similarity(doc_tfidf_vector1, doc_tfidf_vector2)[0,0]

In [26]:
doc_matrix

          doc1      doc2      doc3      doc4      doc5
doc1       NaN  0.620589  0.697151  0.667492  0.407027
doc2  0.620589       NaN  0.551195  0.829235  0.864297
doc3  0.697151  0.551195       NaN  0.592854  0.430355
doc4  0.667492  0.829235  0.592854       NaN  0.760873
doc5  0.407027  0.864297  0.430355  0.760873       NaN

In [27]:
new_documents = documents + ["To make carbonara you need eggs"]

clean_documents = [re.sub(r"[^\w\s]", "", x.replace("\n", "").lower()) for x in new_documents]
clean_documents = [remove_stopwords(doc) for doc in clean_documents]

split_documents = [x.split(" ") for x in clean_documents]
stemmed_documents = [" ".join([stemmer.stem(word) for word in doc]) for doc in split_documents]

# Create a TfidfVectorizer object
vectorizer = TfidfVectorizer()

# Fit and transform the documents
tfidf_matrix = vectorizer.fit_transform(stemmed_documents)

# Get the feature names (words)
feature_names = vectorizer.get_feature_names_out()

# Convert the result to a dense array (optional, but easier to read)
dense_matrix = tfidf_matrix.todense()

# Print the TF-IDF matrix with corresponding words
df = pd.DataFrame(dense_matrix, index=[f"doc{x+1}" for x in range(len(stemmed_documents))], columns=feature_names)

print("\nTF-IDF DataFrame:")
df.round(3)

TF-IDF DataFrame:

,black,carbonara,chees,cream,egg,guancial,ingredi,make,need,pasta,pecorino,pepper,recip,roman,romano,salt,use
doc1,0.280,0.209,0.326,0.000,0.209,0.242,0.326,0.000,0.000,0.242,0.242,0.242,0.326,0.000,0.472,0.242,0.000
doc2,0.269,0.201,0.000,0.000,0.201,0.232,0.314,0.269,0.269,0.232,0.232,0.232,0.314,0.314,0.000,0.232,0.371
doc3,0.296,0.221,0.345,0.499,0.221,0.256,0.000,0.000,0.000,0.256,0.256,0.256,0.345,0.000,0.000,0.256,0.000
doc4,0.289,0.217,0.338,0.000,0.217,0.250,0.338,0.289,0.289,0.250,0.250,0.250,0.000,0.338,0.000,0.250,0.000
doc5,0.000,0.235,0.000,0.000,0.235,0.271,0.000,0.314,0.314,0.271,0.271,0.271,0.000,0.367,0.000,0.271,0.434
doc6,0.000,0.424,0.000,0.000,0.424,0.000,0.000,0.566,0.566,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000

## Information Retrieval Task Example

In [28]:
# Add more recipes to our collection
documents += [

    """
    To prepare amatriciana you need pasta, guanciale, peeled tomatoes, roman pecorino cheese.
    """,

    """
    Ingredients for amatriciana: guanciale, pasta, tomato sauce, pecorino romano DOP and black pepper.
    """,

    """
    Pasta all'amatriciana - ingredients: guanciale, white wine, peeled tomatoes, pecorino, pasta.
    """
    
]

In [29]:
clean_documents = [re.sub(r"[^\w\s]", "", x.replace("\n", "").lower()) for x in documents]
clean_documents = [remove_stopwords(doc) for doc in clean_documents]

split_documents = [x.split(" ") for x in clean_documents]
stemmed_documents = [" ".join([stemmer.stem(word) for word in doc]) for doc in split_documents]

# Create a TfidfVectorizer object
vectorizer = TfidfVectorizer()

# Fit and transform the documents
tfidf_matrix = vectorizer.fit_transform(stemmed_documents)

# Get the feature names (words)
feature_names = vectorizer.get_feature_names_out()

# Convert the result to a dense array (optional, but easier to read)
dense_matrix = tfidf_matrix.todense()

# Print the TF-IDF matrix with corresponding words
df = pd.DataFrame(dense_matrix, index=[f"doc{x+1}" for x in range(len(stemmed_documents))], columns=feature_names)

print("\nTF-IDF DataFrame:")
df.round(3)

TF-IDF DataFrame:

,allamatriciana,amatriciana,black,carbonara,chees,cream,dop,egg,guancial,ingredi,make,need,pasta,pecorino,peel,pepper,prepar,recip,roman,romano,salt,sauc,tomato,use,white,wine
doc1,0.000,0.000,0.283,0.283,0.320,0.000,0.000,0.283,0.201,0.283,0.000,0.000,0.201,0.201,0.000,0.252,0.000,0.365,0.000,0.423,0.283,0.000,0.000,0.000,0.000,0.000
doc2,0.000,0.000,0.255,0.255,0.000,0.000,0.000,0.255,0.181,0.255,0.328,0.288,0.181,0.181,0.000,0.227,0.000,0.328,0.288,0.000,0.255,0.000,0.000,0.380,0.000,0.000
doc3,0.000,0.000,0.284,0.284,0.321,0.506,0.000,0.284,0.202,0.000,0.000,0.000,0.202,0.202,0.000,0.253,0.000,0.366,0.000,0.000,0.284,0.000,0.000,0.000,0.000,0.000
doc4,0.000,0.000,0.280,0.280,0.316,0.000,0.000,0.280,0.199,0.280,0.360,0.316,0.199,0.199,0.000,0.249,0.000,0.000,0.316,0.000,0.280,0.000,0.000,0.000,0.000,0.000
doc5,0.000,0.000,0.000,0.292,0.000,0.000,0.000,0.292,0.208,0.000,0.376,0.330,0.208,0.208,0.000,0.260,0.000,0.000,0.330,0.000,0.292,0.000,0.000,0.436,0.000,0.000
doc6,0.000,0.390,0.000,0.000,0.295,0.000,0.000,0.000,0.186,0.000,0.000,0.295,0.186,0.186,0.390,0.000,0.466,0.000,0.295,0.000,0.000,0.000,0.337,0.000,0.000,0.000
doc7,0.000,0.365,0.244,0.000,0.000,0.000,0.435,0.000,0.174,0.244,0.000,0.000,0.174,0.174,0.000,0.217,0.000,0.000,0.000,0.365,0.000,0.435,0.315,0.000,0.000,0.000
doc8,0.427,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.170,0.239,0.000,0.000,0.341,0.170,0.357,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.308,0.000,0.427,0.427

In [30]:
query = "how do I prepare amatriciana pasta?"

print(query)

how do I prepare amatriciana pasta?

In [31]:
# Preprocess query and perform tf-idf
clean_query = re.sub(r"[^\w\s]", "", query.replace("\n", "").lower())
split_query = clean_query.split(" ")
stemmed_query = " ".join([stemmer.stem(word) for word in split_query])

vector_query = vectorizer.transform([stemmed_query])

dense_query = vector_query.todense()

In [32]:
# Rank our documents based on similarity with respect to our query
rank = pd.DataFrame(index=[f"doc{x+1}" for x in range(len(stemmed_documents))], columns=["score"])

for _id, doc in enumerate([f"doc{x+1}" for x in range(len(stemmed_documents))]):
    doc_tfidf_vector = tfidf_matrix[_id,:].toarray().reshape(1, -1)
    query_tfidf_vector = vector_query.toarray().reshape(1,-1)
    rank.loc[doc, "score"] = cosine_similarity(query_tfidf_vector, doc_tfidf_vector)[0, 0]

In [33]:
# Select top4 relevant documents
rank = rank.sort_values("score", ascending=False)
rank["selected"] = [1] * 4 + [0] * (len(rank)-4)
rank["relevant"] = [1] * 3 + [0] * (len(rank)-3)
rank

         score  selected  relevant
doc6  0.635347         1         1
doc7  0.274726         1         1
doc8  0.099698         1         1
doc5  0.060739         1         0
doc3  0.059083         0         0
doc1  0.058952         0         0
doc4  0.058203         0         0
doc2   0.05304         0         0

In [34]:
# Evaluate precision and recall of our search task. What can we say about these metrics?
from sklearn.metrics import precision_score, recall_score

print(f"The precision of our retrieval task is {precision_score(rank[['selected']], rank[['relevant']])*100}%")
print(f"The recall of our retrieval task is {recall_score(rank[['selected']], rank[['relevant']])*100}%")

The precision of our retrieval task is 100.0%
The recall of our retrieval task is 75.0%

# Tokenization in Text Mining

## What is Tokenization?
Tokenization is the process of breaking down text into smaller units called **tokens**. These tokens can be **words**, **sentences**, or **subwords**, depending on the approach used.

## Why is Tokenization Important?
- It is the first step in **Natural Language Processing (NLP)**.
- Helps in **text analysis, search engines, chatbots, and machine learning models**.
- Makes it easier to process and analyze textual data.

## Types of Tokenization:
1. **Word Tokenization**: Splitting text into individual words.
2. **Sentence Tokenization**: Splitting text into sentences.
3. **Subword Tokenization**: Splitting words into smaller meaningful parts (used in deep learning models like BERT).

In [35]:
import nltk
from nltk.tokenize import word_tokenize

text = "One cannot be too careful with words, they change their minds just as people do."
word_tokens = word_tokenize(text)
print(f"text: {text}")
print("Word Tokens:", word_tokens)
print("\n")

### Code Cell: Sentence Tokenization with NLTK
from nltk.tokenize import sent_tokenize

text = "War is peace. Freedom is slavery. Ignorance is strength."
sent_tokens = sent_tokenize(text)
print(f"text: {text}")
print("Sentence Tokens:", sent_tokens)

text: One cannot be too careful with words, they change their minds just as people do.
Word Tokens: ['One', 'can', 'not', 'be', 'too', 'careful', 'with', 'words', ',', 'they', 'change', 'their', 'minds', 'just', 'as', 'people', 'do', '.']


text: War is peace. Freedom is slavery. Ignorance is strength.
Sentence Tokens: ['War is peace.', 'Freedom is slavery.', 'Ignorance is strength.']

In [36]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
text = "Tokenization is crucial for modern text-mining models."
tokens = tokenizer.tokenize(text)
print("Subword Tokens:", tokens)

Subword Tokens: ['token', '##ization', 'is', 'crucial', 'for', 'modern', 'text', '-', 'mining', 'models', '.']

# Attention Mechanism

The **Attention Mechanism** is a technique that allows models to focus on specific parts of an input sequence when making predictions, rather than processing the entire sequence uniformly. This mechanism is especially useful in tasks like machine translation, summarization, and other sequence-to-sequence tasks.

In traditional sequence models like Recurrent Neural Networks (RNNs) and Long Short-Term Memory (LSTM), each input is processed sequentially. The attention mechanism enhances this by enabling the model to focus on important words or tokens from the input sequence while making predictions at each step.

In [37]:
from transformers import BertModel, BertTokenizer
from bertviz import head_view
import torch

In [38]:
text = """
The kid was playing with the ball. Then he threw it at his grandma.
"""

print(text)

The kid was playing with the ball. Then he threw it at his grandma.

In [39]:
import torch

# Let's load a vanilla BERT-base model. 
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

In [40]:
tokens = tokenizer.encode(text)
inputs = torch.tensor(tokens).unsqueeze(0) # unsqueeze changes the shape from (20,) -> (1, 20)
inputs

tensor([[  101,  1996,  4845,  2001,  2652,  2007,  1996,  3608,  1012,  2059,
          2002,  4711,  2009,  2012,  2010, 13055,  1012,   102]])

In [41]:
attention = model(inputs, output_attentions=True)[2]

BertSdpaSelfAttention is used but `torch.nn.functional.scaled_dot_product_attention` does not support non-absolute `position_embedding_type` or `output_attentions=True` or `head_mask`. Falling back to the manual attention implementation, but specifying the manual implementation will be required from Transformers version v5.0.0 onwards. This warning can be removed using the argument `attn_implementation="eager"` when loading the model.

In [42]:
tokens_as_list = tokenizer.convert_ids_to_tokens(inputs[0])
head_view(attention, tokens_as_list)

# Transformer Architectures: Encoder-Decoder, BERT, GPT

Transformers are a type of neural network architecture that revolutionized natural language processing (NLP). They rely on the **attention mechanism** to process input data in parallel (unlike older sequential models like RNNs), making them faster and more effective for tasks like translation, summarization, and text generation.

---

## Key Components of Transformers

1. **Encoder**:  
   - The encoder processes the input data (e.g., a sentence) and converts it into a set of hidden representations (vectors) that capture the meaning of the input.  
   - It uses **self-attention** to understand relationships between all words in the input, regardless of their distance from each other.

2. **Decoder**:  
   - The decoder generates output data (e.g., a translated sentence) based on the encoder's hidden representations.  
   - It also uses self-attention but adds an extra step to focus on the encoder's output, ensuring the generated output is aligned with the input.
  

![Alt text](https://aiml.com/wp-content/uploads/2023/09/Annotated-Transformers-Architecture.png)

---

## Encoder-Decoder Architecture

The original Transformer model (introduced in the paper *"Attention is All You Need"*) uses both an encoder and a decoder. This architecture is ideal for **sequence-to-sequence tasks**, such as:
- **Machine Translation**: Translating a sentence from one language to another.
- **Text Summarization**: Generating a shorter version of a long document.

---

## BERT vs. GPT: Two Popular Transformer Variants

While both BERT and GPT are based on the Transformer architecture, they are designed for different purposes:

### BERT (Bidirectional Encoder Representations from Transformers)
- **Architecture**: Uses only the **encoder** part of the Transformer.
- **Key Feature**: Bidirectional attention, meaning it looks at both the left and right context of a word simultaneously. This makes BERT great for understanding the meaning of words in context.
- **Use Cases**:  
  - Sentence classification (e.g., spam detection).  
  - Question answering (e.g., finding answers in a paragraph).  
  - Named entity recognition (e.g., identifying names, dates, or locations in text).

### GPT (Generative Pre-trained Transformer)
- **Architecture**: Uses only the **decoder** part of the Transformer.
- **Key Feature**: Unidirectional attention, meaning it processes text from left to right. This makes GPT excellent for generating coherent and contextually relevant text.
- **Use Cases**:  
  - Text generation (e.g., writing essays, stories, or code).  
  - Chatbots and conversational AI.  
  - Autocompletion (e.g., suggesting the next word in a sentence).

---

## Summary

| Feature               | BERT (Encoder)                     | GPT (Decoder)                     |
|-----------------------|------------------------------------|------------------------------------|
| **Attention**         | Bidirectional (looks at both sides)| Unidirectional (left-to-right)    |
| **Use Case**          | Understanding text                 | Generating text                   |
| **Example Tasks**     | Question answering, classification | Text generation, chatbots         |

Transformers have become the backbone of modern NLP, and understanding their architecture and variants (like BERT and GPT) is key to leveraging their power for real-world applications.

# References

- https://www.ibm.com/think/insights/managing-unstructured-data
- https://machinelearningmastery.com/gentle-introduction-bag-words-model/ (Bag of Words deep dive)
- https://en.wikipedia.org/wiki/Tf%E2%80%93idf (tf-idf wiki)
- https://www.kopp-online-marketing.com/what-is-bm25 (more powerful representation with bm25)
- https://www.geeksforgeeks.org/python-lemmatization-with-nltk/ (lemmatization, a further preprocessing step wrt stemming)
- https://spotintelligence.com/2023/09/07/vector-space-model/ (Vector space model for documents)

- https://arxiv.org/abs/1706.03762 (Attention is all you need - first paper on transformers)
- https://huggingface.co (transformers platform)
- https://h2o.ai/wiki/bert/ (BERT deep dive)
- https://www.ibm.com/think/topics/gpt (GPT deep dive)

### Other NLP Tasks
- https://www.techtarget.com/searchbusinessanalytics/definition/opinion-mining-sentiment-mining (Sentiment Analysis)
- https://huggingface.co/tasks/text-classification (Text Classification)